# Generated by Django 3.2.13 on 2022-12-03 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Physical',
            fields=[
                ('PhysicalId', models.AutoField(primary_key=True, serialize=False)),
                ('PhysicalVoltage', models.FloatField()),
                ('PhysicalCurrent', models.FloatField()),
                ('PhysicalTemperature', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('StatusId', models.AutoField(primary_key=True, serialize=False)),
                ('StatusBattery', models.IntegerField()),
                ('StatusPercent', models.FloatField()),
            ],
        ),
    ]
