# Generated by Django 4.1.3 on 2022-12-06 09:07

import BatteryApplication.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Battery',
            fields=[
                ('dateTime', models.DateTimeField(auto_created=True, auto_now_add=True, null=True)),
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('Sensor', djongo.models.fields.EmbeddedField(blank=True, model_container=BatteryApplication.models.Sensor, null=True)),
                ('Calculate', djongo.models.fields.EmbeddedField(blank=True, model_container=BatteryApplication.models.Calculate, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Calculate',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('Status', models.CharField(blank=True, max_length=2, null=True)),
                ('Percent', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Physical',
            fields=[
                ('PhysicalId', models.AutoField(primary_key=True, serialize=False)),
                ('PhysicalVoltage', models.FloatField()),
                ('PhysicalCurrent', models.FloatField()),
                ('PhysicalTemperature', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('Voltage', models.FloatField(blank=True, null=True)),
                ('Current', models.FloatField(blank=True, null=True)),
                ('Temperature', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('StatusId', models.AutoField(primary_key=True, serialize=False)),
                ('StatusBattery', models.IntegerField()),
                ('StatusPercent', models.FloatField()),
            ],
        ),
    ]
