# Generated by Django 3.2.13 on 2022-11-15 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BatteryApplication', '0002_charge_chargecurrent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Charge',
            new_name='Physical',
        ),
        migrations.RenameField(
            model_name='physical',
            old_name='ChargeCurrent',
            new_name='PhysicalCurrent',
        ),
        migrations.RenameField(
            model_name='physical',
            old_name='ChargeId',
            new_name='PhysicalId',
        ),
        migrations.RenameField(
            model_name='physical',
            old_name='ChargePercent',
            new_name='PhysicalTemperature',
        ),
        migrations.RenameField(
            model_name='physical',
            old_name='ChargeVoltage',
            new_name='PhysicalVoltage',
        ),
        migrations.AddField(
            model_name='status',
            name='StatusPercent',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
