# Generated by Django 4.1.3 on 2022-12-11 10:10

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('dateTime', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('Decision', models.CharField(max_length=1)),
                ('Priority', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Remote',
            fields=[
                ('dateTime', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('Decision', models.CharField(max_length=1)),
                ('Priority', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('dateTime', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('Decision', models.CharField(max_length=1)),
                ('Priority', models.CharField(max_length=1)),
            ],
        ),
    ]
