# Generated by Django 3.2.13 on 2022-12-03 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('AdministratorId', models.AutoField(primary_key=True, serialize=False)),
                ('AdministratorDecision', models.IntegerField()),
                ('AdministratorPriority', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Remote',
            fields=[
                ('RemoteId', models.AutoField(primary_key=True, serialize=False)),
                ('RemoteDecision', models.IntegerField()),
                ('RemotePriority', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('RobotId', models.AutoField(primary_key=True, serialize=False)),
                ('RobotDecision', models.IntegerField()),
                ('RobotPriority', models.IntegerField()),
            ],
        ),
    ]
