# Generated by Django 4.1.3 on 2022-12-11 11:07

import PositionApplication.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fiducial',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('Mark', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GlobalPosition',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('X', models.FloatField(blank=True, null=True)),
                ('Y', models.FloatField(blank=True, null=True)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gyroscope',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('Angle', models.FloatField(blank=True, null=True)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Odometry',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('Left', models.FloatField(blank=True, null=True)),
                ('Right', models.FloatField(blank=True, null=True)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('dateTime', models.DateTimeField(auto_created=True, auto_now_add=True, null=True)),
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('Odometry', djongo.models.fields.EmbeddedField(blank=True, model_container=PositionApplication.models.Odometry, null=True)),
                ('Fiducial', djongo.models.fields.EmbeddedField(blank=True, model_container=PositionApplication.models.Fiducial, null=True)),
                ('Gyroscope', djongo.models.fields.EmbeddedField(blank=True, model_container=PositionApplication.models.Gyroscope, null=True)),
                ('GlobalPosition', djongo.models.fields.EmbeddedField(blank=True, model_container=PositionApplication.models.GlobalPosition, null=True)),
            ],
        ),
    ]
