# Generated by Django 4.1.3 on 2022-12-05 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fiducial',
            fields=[
                ('FiducialId', models.AutoField(primary_key=True, serialize=False)),
                ('FiducialMark', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GlobalPosition',
            fields=[
                ('GlobalPositionId', models.AutoField(primary_key=True, serialize=False)),
                ('GlobalPositionX', models.IntegerField()),
                ('GlobalPositionY', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Gyroscope',
            fields=[
                ('GyroscopeId', models.AutoField(primary_key=True, serialize=False)),
                ('GyroscopeAngle', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Odometry',
            fields=[
                ('OdometryId', models.AutoField(primary_key=True, serialize=False)),
                ('OdometryLeft', models.IntegerField()),
                ('OdometryRight', models.IntegerField()),
            ],
        ),
    ]
