# Generated by Django 4.1.3 on 2022-12-20 12:13

import MotorApplication.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Current',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('Left', models.FloatField(blank=True, null=True)),
                ('Right', models.FloatField(blank=True, null=True)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Power',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('Left', models.FloatField(blank=True, null=True)),
                ('Right', models.FloatField(blank=True, null=True)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PWM',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('Left', models.FloatField(blank=True, null=True)),
                ('Right', models.FloatField(blank=True, null=True)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Voltage',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('Left', models.FloatField(blank=True, null=True)),
                ('Right', models.FloatField(blank=True, null=True)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Motor',
            fields=[
                ('dateTime', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('PWM', djongo.models.fields.EmbeddedField(blank=True, model_container=MotorApplication.models.PWM, null=True)),
                ('Voltage', djongo.models.fields.EmbeddedField(blank=True, model_container=MotorApplication.models.Voltage, null=True)),
                ('Current', djongo.models.fields.EmbeddedField(blank=True, model_container=MotorApplication.models.Current, null=True)),
                ('Power', djongo.models.fields.EmbeddedField(blank=True, model_container=MotorApplication.models.Power, null=True)),
            ],
        ),
    ]
