# Generated by Django 4.1.3 on 2022-12-11 11:07

import RouteApplication.models
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PositionApplication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('Distance', models.FloatField(blank=True, null=True)),
                ('Consumption', models.FloatField(blank=True, null=True)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('dateTime', models.DateTimeField(auto_created=True, auto_now_add=True, null=True)),
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('Estimated', djongo.models.fields.EmbeddedField(blank=True, model_container=RouteApplication.models.Data, null=True)),
                ('Real', djongo.models.fields.EmbeddedField(blank=True, model_container=RouteApplication.models.Data, null=True)),
                ('EndPoint', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='End', to='PositionApplication.position')),
                ('StartPoint', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Start', to='PositionApplication.position')),
            ],
        ),
    ]
