# Generated by Django 4.1.3 on 2022-12-05 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('RouteId', models.AutoField(primary_key=True, serialize=False)),
                ('RouteDistanceEstimated', models.FloatField()),
                ('RouteConsumptionEstimated', models.FloatField()),
                ('RouteDistanceReal', models.FloatField()),
                ('RouteConsumptionReal', models.FloatField()),
            ],
        ),
    ]
