# Generated by Django 4.1.3 on 2022-12-05 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actions',
            fields=[
                ('ActionsId', models.AutoField(primary_key=True, serialize=False)),
                ('ActionsAction', models.IntegerField()),
                ('ActionsStatus', models.IntegerField()),
                ('ActionsPriority', models.IntegerField()),
                ('ActionsSource', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('QueueId', models.AutoField(primary_key=True, serialize=False)),
                ('QueueStatus', models.IntegerField()),
                ('ActionsId', models.IntegerField()),
            ],
        ),
    ]
