# Generated by Django 3.2.13 on 2022-12-02 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actions',
            fields=[
                ('ActionsId', models.AutoField(primary_key=True, serialize=False)),
                ('ActionsAction', models.IntegerField()),
                ('ActionsStatus', models.IntegerField()),
                ('ActionsPriority', models.IntegerField()),
                ('ActionsSource', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('QueueId', models.AutoField(primary_key=True, serialize=False)),
                ('QueueStatus', models.IntegerField()),
                ('ActionsId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='ActionsApplication.actions')),
            ],
        ),
    ]
