# Generated by Django 3.2.13 on 2022-11-28 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActionsApplication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actions',
            name='ActionsAction',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
