# Generated by Django 3.2.13 on 2022-12-02 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActionsApplication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='ActionsId',
            field=models.IntegerField(),
        ),
    ]
