# Generated by Django 3.2.13 on 2022-11-30 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ActionsApplication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actions',
            name='ActionsAction',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('QueueId', models.AutoField(primary_key=True, serialize=False)),
                ('QueueStatus', models.IntegerField()),
                ('ActionsId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='ActionsApplication.actions')),
            ],
        ),
    ]
