# Generated by Django 3.2.13 on 2022-11-28 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActionsApplication', '0002_actions_actionsaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('QueueId', models.AutoField(primary_key=True, serialize=False)),
                ('ActionsId', models.IntegerField()),
            ],
        ),
    ]
