# Generated by Django 3.2.13 on 2022-11-28 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ActionsApplication', '0003_queue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queue',
            name='ActionsId',
        ),
    ]
