# Generated by Django 3.2.13 on 2022-11-28 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActionsApplication', '0004_remove_queue_actionsid'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='ActionsId',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
