# Generated by Django 3.2.13 on 2022-11-30 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActionsApplication', '0005_queue_actionsid'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='QueueStatus',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
