# Generated by Django 4.1.3 on 2022-11-14 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employes',
            new_name='Employees',
        ),
        migrations.RenameField(
            model_name='employees',
            old_name='EmployesId',
            new_name='EmployeesId',
        ),
        migrations.RenameField(
            model_name='employees',
            old_name='EmployesName',
            new_name='EmployeesName',
        ),
    ]
