# Generated by Django 3.2.13 on 2022-11-24 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actions',
            fields=[
                ('ActionsId', models.AutoField(primary_key=True, serialize=False)),
                ('ActionsStatus', models.IntegerField()),
                ('ActionsPriority', models.IntegerField()),
                ('ActionsSource', models.IntegerField()),
            ],
        ),
    ]
