# Generated by Django 3.2.13 on 2022-11-15 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PositionApplication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiducial',
            name='FiducialMark',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='gyroscope',
            name='GyroscopeAngle',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='odometry',
            name='OdometryLeft',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='odometry',
            name='OdometryRight',
            field=models.IntegerField(),
        ),
    ]
