# Generated by Django 3.2.13 on 2022-11-15 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('ChargeId', models.AutoField(primary_key=True, serialize=False)),
                ('ChargeVoltage', models.FloatField()),
                ('ChargePercent', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('StatusId', models.AutoField(primary_key=True, serialize=False)),
                ('StatusBattery', models.BinaryField()),
            ],
        ),
    ]
