# Generated by Django 3.2.13 on 2022-11-15 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BatteryApplication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge',
            name='ChargeCurrent',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
